name: Kevin's Lab
url: 'https://ajoa2757.github.io'
description: 'tech blog'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Kevin Lee'
disqus_shortname: Kev
# google_analytics: G-NN7JP65RMS

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap


sass:
    sass_dir: _sass
    style: :compressed

highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
  - jekyll-toc
